#!/usr/bin/env bash
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SKILLS_DIR="$REPO_DIR/.claude/skills"

# --- colors ------------------------------------------------------------------
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

# --- helpers -----------------------------------------------------------------
print_header() { echo -e "\n${BOLD}${CYAN}$1${RESET}"; }
print_ok()     { echo -e "  ${GREEN}✔${RESET} $1"; }
print_warn()   { echo -e "  ${YELLOW}⚠${RESET}  $1"; }
print_err()    { echo -e "  ${RED}✘${RESET} $1"; }

# --- step 1: project path ----------------------------------------------------
print_header "Step 1 — Project path"
read -rp "  Enter the project directory path: " PROJECT_PATH

PROJECT_PATH="${PROJECT_PATH/#\~/$HOME}"

if [[ ! -d "$PROJECT_PATH" ]]; then
    print_err "Directory '$PROJECT_PATH' does not exist."
    exit 1
fi
print_ok "Project: $PROJECT_PATH"

# --- step 2: target tool -----------------------------------------------------
print_header "Step 2 — Target tool"
echo "  Select where to install the skills:"
echo ""
echo "  1) .claude/   (Claude Code)"
echo "  2) .gemini/   (Gemini CLI)"
echo "  3) .kiro/     (Kiro)"
echo ""
read -rp "  Choice [1-3]: " tool_choice

case "$tool_choice" in
    1) TOOL="claude";  TARGET_DIR="$PROJECT_PATH/.claude/skills" ;;
    2) TOOL="gemini";  TARGET_DIR="$PROJECT_PATH/.gemini" ;;
    3) TOOL="kiro";    TARGET_DIR="$PROJECT_PATH/.kiro/steering" ;;
    *)
        print_err "Invalid choice."
        exit 1
        ;;
esac
print_ok "Tool: $TOOL → $TARGET_DIR"

# --- step 3: pick skills -----------------------------------------------------
print_header "Step 3 — Select skills to install"

AVAILABLE_SKILLS=()
SKILL_DESCS=()
while IFS= read -r skill_dir; do
    skill_name=$(basename "$skill_dir")
    skill_file="$skill_dir/SKILL.md"
    if [[ -f "$skill_file" ]]; then
        desc=$(grep -m1 '^description:' "$skill_file" | sed 's/^description: //' || echo "")
        AVAILABLE_SKILLS+=("$skill_name")
        SKILL_DESCS+=("$desc")
    fi
done < <(find "$SKILLS_DIR" -mindepth 1 -maxdepth 1 -type d | sort)

echo ""
for i in "${!AVAILABLE_SKILLS[@]}"; do
    printf "  %d) %-12s %s\n" "$((i+1))" "${AVAILABLE_SKILLS[$i]}" "${SKILL_DESCS[$i]}"
done
echo ""
echo "  Enter numbers separated by spaces (e.g: 1 3 4)"
echo "  Press ENTER to install all"
read -rp "  Skills: " skill_input

SELECTED_SKILLS=()
if [[ -z "$skill_input" ]]; then
    SELECTED_SKILLS=("${AVAILABLE_SKILLS[@]}")
else
    for num in $skill_input; do
        idx=$((num - 1))
        if [[ $idx -ge 0 && $idx -lt ${#AVAILABLE_SKILLS[@]} ]]; then
            SELECTED_SKILLS+=("${AVAILABLE_SKILLS[$idx]}")
        else
            print_warn "Invalid number '$num', skipping."
        fi
    done
fi

if [[ ${#SELECTED_SKILLS[@]} -eq 0 ]]; then
    print_err "No skills selected."
    exit 1
fi

echo ""
echo "  Will install: ${SELECTED_SKILLS[*]}"

# --- step 4: install ---------------------------------------------------------
print_header "Step 4 — Installing"

mkdir -p "$TARGET_DIR"

case "$TOOL" in
    claude)
        # Claude Code: each skill goes in its own subfolder as SKILL.md
        for skill in "${SELECTED_SKILLS[@]}"; do
            src="$SKILLS_DIR/$skill/SKILL.md"
            dest_dir="$TARGET_DIR/$skill"
            mkdir -p "$dest_dir"
            cp "$src" "$dest_dir/SKILL.md"
            print_ok "Installed: .claude/skills/$skill/SKILL.md"
        done
        ;;

    gemini)
        # Gemini: concatenate all selected skills into GEMINI.md
        dest="$TARGET_DIR/GEMINI.md"
        echo "# Project Skills — auto-generated by vscode-config/scripts/setup-project.sh" > "$dest"
        echo "# Source: https://github.com/KrohEsteban/vscode-config" >> "$dest"
        for skill in "${SELECTED_SKILLS[@]}"; do
            src="$SKILLS_DIR/$skill/SKILL.md"
            echo "" >> "$dest"
            echo "---" >> "$dest"
            echo "" >> "$dest"
            # Strip frontmatter (lines between first and second ---)
            awk 'BEGIN{fm=0} /^---/{fm++; next} fm!=1{print}' "$src" >> "$dest"
            print_ok "Appended skill: $skill → .gemini/GEMINI.md"
        done
        ;;

    kiro)
        # Kiro: each skill as a separate .md file in .kiro/steering/
        for skill in "${SELECTED_SKILLS[@]}"; do
            src="$SKILLS_DIR/$skill/SKILL.md"
            dest="$TARGET_DIR/${skill}.md"
            # Strip frontmatter
            awk 'BEGIN{fm=0} /^---/{fm++; next} fm!=1{print}' "$src" > "$dest"
            print_ok "Installed: .kiro/steering/${skill}.md"
        done
        ;;
esac

print_header "Done"
echo -e "  ${GREEN}Skills installed in: $TARGET_DIR${RESET}"
echo ""
